### ISSUE TITLE
New mechanic?

### ISSUE THREAD

**Issue by byaka** [GarwelGarwel/KerbalHealth#31]
What about adding some new feautures?
1. Instantly adding some amount of health to specific Kerbal (or all Kerbals).
2. Timeout for activation HelthModule. For example we add new ability to antennas, that do [comm session] with Kerbal's family. This action add some health-points to him, but module [comm session] will be inoperabable for timeout.
3. Timeout (per Kerbal) for effecting Kerbal by cpecific HelthModule. For example we add item [antidepressant] that lower all negative effects for some period, but can't be used again for this Kerbal for timeout.
4. Limit of uses. Can be global and per-Kerbal. Useful for antidepressant, for example.

**Comment by GarwelGarwel** [comment]
I think I may introduce Medical Supplies resource, which can be used to increase health and/or cure certain health conditions. But it's going to take some time and not sooner than the mod reaches 1.0.

**Comment by byaka** [comment]
Simple "Medical Supplies" it so boooring..

**Comment by LouisB3** [comment]
Timeout-based functions that have to be activated manually sound like they are a recipe for micromanagement.

Resource consumption to speed healing sounds interesting, but it might demand that lost HP are tracked by source (MedicalSupplies to reverse sickness, Food/Snacks/etc to reverse starvation, etc.), which might not be desirable due to complexity.

**Comment by GarwelGarwel** [comment]
I don't see any of these implemented in Kerbal Health in the near future, so closing the thread.
