### ISSUE TITLE
Increase radiation levels while around RTGs or Nuclear Engines

### ISSUE THREAD

**Issue by ryaninator81** [GarwelGarwel/KerbalHealth#82]
RTGs and Nuclear Engines create a lot of radiation. Please consider them having a radiation sphere of influence.

**Comment by Blothorn** [comment]
Most RTGs are a negligable radiation threat, as Pu-238 primarily emits easily-blocked alpha particles. Pu-238  RTGs have even been used in pacemakers! Radiation from nuclear engines is already implemented--see the stock part patches. If you were seeing nuclear engines from a mod that were not causing radiation, consider adding a compatibility patch.

**Comment by ryaninator81** [comment]
Ah. I forgot that the RTGs are Plutonium, not Strontium.

**Comment by ryaninator81** [comment]
I found out why I didn’t think the nuclear engines affected radiation levels. The Geiger counters do not reflect the changes due to nuclear engines, you can see me use 3 of them and get the right radiation levels in the health monitor, but not the Geiger counter. (Valentina is in the plane)
![436F9C9B-03C3-4D8F-8C38-D9B18E8F3593](https://user-images.githubusercontent.com/45949859/57490668-36f1c600-7277-11e9-9cbf-991244376eec.jpeg)

**Comment by GarwelGarwel** [comment]
This is expected behavior. First, the point of Geiger counters is to test radiation environment before sending your kerbals in. So it makes sense for them to ignore/screen against intrinsic radiation and only measure natural radiation. Second, the way I implement part radiation makes it quite difficult to calculate its level for uncrewed vessels.

I'm closing this thread now.
